In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

from Funciones import Explorer

In [2]:
DATA_DIR="/home/grupodot/Documentos/Examen_globant/Purchase-Card-Transactions_GLBNT_TESTT/Data/"

In [7]:
expl = Explorer()
df_f = expl.clean_import(DATA_DIR)
print("La dimension de la base es: ", df_f.shape)
df_f.describe()

La dimension de la base es:  (47803, 12)

,TRANS VAT DESC,ORIGINAL GROSS AMT,MERCHANT NAME,CARD NUMBER,TRANS CAC CODE 1,TRANS CAC DESC 1,TRANS CAC CODE 2,TRANS CAC DESC 2,TRANS CAC CODE 3,Directorate,BILLING CUR CODE,Unnamed: 10
count,47803.000000,47803.000000,47803.000000,47803.000000,47803.000000,47803.000000,47803.000000,47803.000000,47803.000000,47803.000000,47803.000000,47803.000000
mean,4.571261,158.331458,2297.651905,552.437169,51.877163,54.656967,388.251951,466.267473,0.244211,7.130891,0.278978,9.617304
std,1.550038,1958.036331,1905.590212,304.734431,21.694383,31.078966,250.273340,264.175416,2.062509,3.287610,0.448502,1.439584
min,0.000000,-6794.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,12.700000,289.000000,299.000000,35.000000,28.000000,179.000000,228.000000,0.000000,6.000000,0.000000,10.000000
50%,6.000000,39.980000,1969.000000,572.000000,55.000000,58.000000,280.000000,432.000000,0.000000,6.000000,0.000000,10.000000
75%,6.000000,85.000000,4162.000000,815.000000,60.000000,84.000000,679.000000,717.000000,0.000000,11.000000,1.000000,10.000000
max,7.000000,106289.880000,5986.000000,1060.000000,105.000000,105.000000,911.000000,904.000000,25.000000,13.000000,1.000000,10.000000

In [12]:
scaler=StandardScaler()
scaler.fit(df_f)
scaled_data=scaler.transform(df_f)
df_f2 = pd.DataFrame(data=scaled_data, columns=df_f.columns)
df_f2.describe()

,TRANS VAT DESC,ORIGINAL GROSS AMT,MERCHANT NAME,CARD NUMBER,TRANS CAC CODE 1,TRANS CAC DESC 1,TRANS CAC CODE 2,TRANS CAC DESC 2,TRANS CAC CODE 3,Directorate,BILLING CUR CODE,Unnamed: 10
count,4.780300e+04,4.780300e+04,4.780300e+04,4.780300e+04,4.780300e+04,4.780300e+04,4.780300e+04,4.780300e+04,4.780300e+04,4.780300e+04,4.780300e+04,4.780300e+04
mean,3.127381e-16,8.918387e-18,9.929137e-17,3.626811e-17,5.945591e-19,-8.086004e-17,-1.189118e-17,1.040478e-16,-6.837430e-18,-4.756473e-17,-3.329531e-17,5.707768e-17
std,1.000010e+00,1.000010e+00,1.000010e+00,1.000010e+00,1.000010e+00,1.000010e+00,1.000010e+00,1.000010e+00,1.000010e+00,1.000010e+00,1.000010e+00,1.000010e+00
min,-2.949159e+00,-3.550702e+00,-1.205756e+00,-1.812867e+00,-2.391297e+00,-1.758667e+00,-1.551328e+00,-1.765010e+00,-1.184058e-01,-2.169043e+00,-6.220296e-01,-6.680683e+00
25%,-1.013702e+00,-7.437706e-02,-1.054095e+00,-8.316744e-01,-7.779589e-01,-8.577263e-01,-8.361024e-01,-9.019384e-01,-1.184058e-01,-3.439895e-01,-6.220296e-01,2.658404e-01
50%,9.217537e-01,-6.044459e-02,-1.724691e-01,6.419700e-02,1.439483e-01,1.075669e-01,-4.325394e-01,-1.297162e-01,-1.184058e-01,-3.439895e-01,-6.220296e-01,2.658404e-01
75%,9.217537e-01,-3.745192e-02,9.783675e-01,8.616210e-01,3.744251e-01,9.441543e-01,1.161734e+00,9.491237e-01,-1.184058e-01,1.176888e+00,1.607641e+00,2.658404e-01
max,1.566906e+00,5.420362e+01,1.935561e+00,1.665608e+00,2.448716e+00,1.619860e+00,2.088730e+00,1.656994e+00,1.200288e+01,1.785239e+00,1.607641e+00,2.658404e-01